### PR TITLE
feat: support overwriting components

### PR DESCRIPTION
**Pull request by Atinux**
The idea came to allow user to overwrites components in the Nuxt Docs Theme: https://github.com/nuxt/content/pull/542

With this PR, we can now have:

```bash
node_modules/
  my-theme/
    components/
      Header.vue
components/
   Header.vue
```

Then defining in the `nuxt.config`:

```js
export default {
  components: [
    '~/components', // default level is 0
   { path: 'node_modules/my-theme/components', level: 1 }
  ]
}
```

Our `components/Header.vue`  will overwrites our theme component if defined since the lowest level overwrites.

### CODE REVIEW

**Comment by pi0** [comment]
Nice idea! But without #81 (full prefix) this is a breaking change since we change behavior by using component from longest path to component with shortest path (actually i think we can have same behavior by changing sort)

**Comment by kevinmarrec** [comment]
Agreed with @pi0 comment.

Something we can do is integrating #81 (full prefix) as default for 2.x with an opt-out flag, and eventually making it opt-in for 1.x first as suggested by @pi0 in the full prefix PR.

We will probably need 2 behaviors concerning this PR (overwriting components) too, depending if full prefix is enabled or not, so it works in both case, OR only have this feature working with full prefix enabled.

**Comment by pperzyna** [comment]
I would love to have it. It is crucial for building bigger apps. 

Is there any workaround for now? How to override components or specific that eg for this folder components have higher priority?

**Comment by Atinux** [comment]
@pperzyna we need to release a new version of @nuxt/components before being able to merge this ;)

**Review by pi0 — APPROVED** [review]

**Pull request merged**
