### PR TITLE
feat!: prefix components in nested dirs with full path

### LINKED ISSUE #67: Auto prefex component name from parent directories
With a complicated website, it's common to have lots of components in many different directories (see screenshot for example).

It would be great to allow for auto-prefix'ing of component names, based on parent directories.

I imagine it could work like this:

```
export default {
    components: [{ path: "~/components", prefix: true }]
}
```

So if you had this directory structure:

```
- /components
- - /block
- - - Work.vue

- - /form
- - - /group
- - - - Radios.vue
```

You'd get `<block-work>` and `</form-group-radios>` as components automatically.

Screen Shot 2020-07-03 at 2 26 38 PM

### PR DESCRIPTION
**Pull request by pi0**
Resolves #67. Despite the documentation, we were not properly resolving component names from nested directories resulting in duplicate names. This PR is probably introducing regression in usage for current users so would be probably introduce at least as feat.

`components/form/input/text.vue`
- Previously: `<InputText>`
- Now: `<FormInputText>`

### CODE REVIEW

**Comment by kevinmarrec** [comment]
@pi0 I thought we didn't want to prefix nested dirs when no duplicated components have been found in other components paths, no ?

**Comment by pi0** [comment]
@kevinmarrec Yes we do warn about duplicated names. Also, it is better that people using distinct names for components (like `<LayoutFormTextArea>` to avoid conflicts.

This PR is to prefix properly for nested dirs like we currently automatically for one level only :)

**Comment by kevinmarrec** [comment]
@pi0 Hum.. for my project at work our components have each a folder with same name that contains `.vue` and `.scss`, it's just gonna be a PINA for us 😅😂

**Comment by pi0** [comment]
@kevinmarrec Actually multifile is still supported to split components :D But seems it is going to be a breaking change. Will move behind a flag for 1.x.

**Comment by Atinux** [comment]
Might be nice to update the documentation I suppose

**Comment by drewbaker** [comment]
Would love to see this merged!

**Comment by drewbaker** [comment]
@pi0 whats happening with this? Any reason it hasn't been merged yet?

**Comment by Atinux** [comment]
@drewbaker we did not merge it yet because it is actually a breaking change and will have to be a major version 😬

**Pull request merged**
