### PR TITLE
fix: transform to PascalCase only on first lower letter or name contains hyphens

### PR DESCRIPTION
**Pull request by manniL**
See #127

### CODE REVIEW

**Review by pi0 — CHANGES_REQUESTED** [review]
I think it would be much better if we introduce fix as a pascal case utility so we can directly unit test it instead of adding logic directly to scanner...

**Comment by manniL** [comment]
> I think it would be much better if we introduce fix as a pascal case utility so we can directly unit test it instead of adding logic directly to scanner...

Fully agreed! Moving the logic into the the pascalCase function.

**Review by pi0 — APPROVED** [review]

**Comment by Atinux** [comment]
Nice work @manniL 🙌

**Comment by manniL** [comment]
Thanks ❤️

**Pull request merged**
